package main

// Build Morse table
func buildMorseTable() map[rune]Morse {
	table := map[rune]Morse{
		'A':  {".-", "DLDDD", "", 4, 1},
		'B':  {"-...", "DDDLDLDLD", "", 6, 3},
		'C':  {"-.-.", "DDDLDLDDDLD", "", 8, 3},
		'D':  {"-..", "DDDLDLD", "", 5, 2},
		'E':  {".", "D", "", 1, 0},
		'F':  {"..-.", "DLDLDDDLD", "", 6, 3},
		'G':  {"--.", "DDDLDDDLD", "", 7, 2},
		'H':  {"....", "DLDLDLD", "", 4, 3},
		'I':  {"..", "DLD", "", 2, 1},
		'J':  {".---", "DLDDDLDDDLDDD", "", 10, 3},
		'K':  {"-.-", "DDDLDLDDD", "", 7, 2},
		'L':  {".-..", "DLDDDLDLD", "", 6, 3},
		'M':  {"--", "DDDLDDD", "", 6, 1},
		'N':  {"-.", "DDDLD", "", 4, 1},
		'O':  {"---", "DDDLDDDLDDD", "", 9, 2},
		'P':  {".--.", "DLDDDLDDDLD", "", 8, 3},
		'Q':  {"--.-", "DDDLDDDLDLDDD", "", 10, 3},
		'R':  {".-.", "DLDDDLD", "", 5, 2},
		'S':  {"...", "DLDLD", "", 3, 2},
		'T':  {"-", "DDD", "", 3, 0},
		'U':  {"..-", "DLDLDDD", "", 5, 2},
		'V':  {"...-", "DLDLDLDDD", "", 6, 3},
		'W':  {".--", "DLDDDLDDD", "", 7, 2},
		'X':  {"-..-", "DDDLDLDLDDD", "", 8, 3},
		'Y':  {"-.--", "DDDLDLDDDLDDD", "", 10, 3},
		'Z':  {"--..", "DDDLDDDLDLD", "", 8, 3},
		'0':  {"-----", "DDDLDDDLDDDLDDDLDDD", "", 15, 4},
		'1':  {".----", "DLDDDLDDDLDDDLDDD", "", 13, 4},
		'2':  {"..---", "DLDLDDDLDDDLDDD", "", 11, 4},
		'3':  {"...--", "DLDLDLDDDLDDD", "", 9, 4},
		'4':  {"....-", "DLDLDLDLDDD", "", 7, 4},
		'5':  {".....", "DLDLDLDLD", "", 5, 4},
		'6':  {"-....", "DDDLDLDLDLD", "", 7, 4},
		'7':  {"--...", "DDDLDDDLDLDLD", "", 9, 4},
		'8':  {"---..", "DDDLDDDLDDDLDLD", "", 11, 4},
		'9':  {"----.", "DDDLDDDLDDDLDDDLD", "", 13, 4},
		'.':  {".-.-.-", "DLDDDLDLDDDLDLDDD", "", 12, 5},
		',':  {"--..--", "DDDLDDDLDLDLDDDLDDD", "", 14, 5},
		'?':  {"..--..", "DLDLDDDLDDDLDLD", "", 10, 5},
		'/':  {"-..-.", "DDDLDLDLDDDLD", "", 9, 4},
		'=':  {"-...-", "DDDLDLDLDLDDD", "", 9, 4},
		'-':  {"-....-", "DDDLDLDLDLDLDDD", "", 10, 4},
		'+':  {".-.-.", "DLDDDLDLDDDLD", "", 9, 4},
		':':  {"---...", "DDDLDDDLDDDLDLDLD", "", 12, 5},
		';':  {"-.-.-.", "DDDLDLDDDLDLDDDLD", "", 12, 5},
		'"':  {".-..-.", "DLDDDLDLDLDDDLD", "", 10, 5},
		'\'': {".-----.", "DLDDDLDDDLDDDLDDDLDDDLD", "", 17, 6},
		'@':  {".--.-.", "DLDDDLDDDLDLDDDLD", "", 12, 5},
		'*':  {"...---...", "DLDLDLDDDLDDDLDDDLDLDLD", "", 15, 8}, // chear use * as <SOS>
		' ':  {"         ", "LLLLLLL", "", 0, 7},
	}

	return table
}
